import React, { useState, useEffect } from 'react';
import {useParams} from 'react-router-dom';
import { academic_session_channel } from '../constants/channels';


const Report = () => {
    const { termId:term_id, levelId:level_id, studentId:student_id } = useParams();

    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    const [report,setReport] = useState(null);

    const loadManifest = async()=>{

        if(!loading) return;

        setLoading(false);

        try{
            const data = await window.api.request(academic_session_channel.getTermReport, { term_id, level_id, student_id })

            setReport(() => data);
        }catch(err){
            console.error(err.message);
            setError("Could not prepare student report, make sure the inputs are complete")
        }
          
    }


    useEffect(() => {
        loadManifest()
    }, []);


    console.log(report);


    return (
        <div className='report_footer'>
            <span>
                &copy; {new Date().getFullYear()},
            </span>


            <span><small>generated by</small> Mirage School Software</span>
        </div>
    )
}

export default Report